[package]
name = "d12a"
version = "0.1.0"
authors = ["JEACO <jeaco@orsted.dk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
